VAS-CRP/Controllers/AuthController.cs
using Auth.Model;
using Auth.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VAS_CRP.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult RequestLogin()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(CustomAccountViewModel cred)
        {
            CustomAccountModel cam = new CustomAccountModel();

            if (cam.login(cred.acct.Username, cred.acct.password) != null)
            {
                Session["Username"] = cred.acct.Username;
                SessionPersister.username = cred.acct.Username;
                //return RedirectToAction("../OnSDPSvcRpt/KuwaitZainOnSDPReport");
                return RedirectToAction("Welcome","Home");
            }
            ViewBag.InvalidCredential = "Invalid Username or Password ";
            return View("Login");
        }

        [HttpGet]
        public ActionResult Logout()
        {
            SessionPersister.username = string.Empty;
            return RedirectToAction("Login","Auth");
        }
        public ActionResult NotAuthorized()
        {
            return View();
        }

    }
}

VAS-CRP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VAS_CRP.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Welcome()
        {
            return View();
        }
    }
}

VAS-CRP/Controllers/OnSDPSvcRptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnSDPSvc.Infrastructure;
using VAS_CRP.ViewModel;
using Auth.Security;

namespace VAS_CRP.Controllers
{
    [CustomAuthorizeAttribute(Roles = "VASTech,OGVAS")]
    public class OnSDPSvcRptController : Controller
    {
        SSReport SSR = new SSReport();
        public ActionResult OnSDPSvc()
        {
            OnSDPSvcs SDPsvc = new OnSDPSvcs();
            return View(SDPsvc);
        }
        [HttpPost]
        public ActionResult SplSvcDet(string Country,string Operator,string ReportType, string FromDate, string ToDate)
        {
            if(Country=="Kuwait" & Operator=="Zain")
            { ViewBag.Report = "Kuwait Zain OnSDP Services Report"; }
            else if (Country == "Kuwait" & Operator == "Operator")
            { ViewBag.Report = "Kuwait Ooredoo OnSDP Services Report"; }
            else if(Country == "Iraq" & Operator == "Zain")
            { ViewBag.Report = "Iraq Zain OnSDP Services Report"; }
            //SSR.GetSplSvcDet(Country, Operator, ReportType, FromDate, ToDate);
            return PartialView("_SplSvcDetails" , SSR.GetSplSvcDet(Country, Operator, ReportType, FromDate, ToDate));
        }

        public ActionResult KuwaitZainOnSDPReport()
        {
            ViewBag.Report = "Kuwait Zain OnSDP Services Report";
            //SplSvcDetails SS= SSR.GetSplSvcDetails("Kuwait", "Zain");
            return View("SplSvcDetails",SSR.GetSplSvcDetails("Kuwait", "Zain"));
        }
        public ActionResult KuwaitOoredooOnSDPReport()
        {
            ViewBag.Report = "Kuwait Ooredoo OnSDP Services Report";
            //SSR.GetSplSvcDetails("Kuwait", "Ooredoo");
            return View("SplSvcDetails", SSR.GetSplSvcDetails("Kuwait", "Ooredoo"));
        }
        public ActionResult IraqZainOnSDPReport()
        {
            ViewBag.Report = "Iraq Zain OnSDP Services Report";
            //SSR.GetSplSvcDetails("Iraq", "Zain");
            return View("SplSvcDetails", SSR.GetSplSvcDetails("Iraq", "Zain"));
        }
        //[HttpPost]
        //public PartialViewResult SSReportDetails(string Country, string Operator, string ReportType)
        //{
        //    //if (ReportType == "Special Services Details")
        //    //{
        //    //    return PartialView("_SSDetails", SSR.GetSpecialServiceDetails(Country, Operator));
        //    //}
        //    //else //(ReportType == "Special Services Subscribers")
        //    //{
        //    //    return PartialView("_SSSubscribers", SSR.GetSpecialServicesSubscribersDetails(Country, Operator));
        //    //}
        //    return PartialView();
        //}
        [HttpPost]
        public JsonResult GetOperatorList(string Country)
        {
            List<SelectListItem> OL = new List<SelectListItem>();
            switch (Country)
            {
                case "Kuwait":
                    OL.Add(new SelectListItem { Text = "Zain", Value = "Zain" });
                    OL.Add(new SelectListItem { Text = "Ooredoo", Value = "Ooredoo" });
                    return Json(OL, JsonRequestBehavior.AllowGet);
                case "Iraq":
                    OL.Add(new SelectListItem { Text = "Zain", Value = "Zain" });
                    return Json(OL, JsonRequestBehavior.AllowGet);
                default:
                    return Json("");
            }
        }
    }
}

VAS-CRP/Views/Home/Welcome.cshtml
@{
    ViewBag.Title = "Welcome";
}

<h5>Please use the side navigation for Reports</h5>

VAS-CRP/Views/OnSDPSvcRpt/OnSDPSvc.cshtml
@model VAS_CRP.ViewModel.OnSDPSvcs

@{
    ViewBag.Title = "OnSDPSvc";
}

<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-4 col-md-offset-4">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title ">OnSDP Services</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->

                @using (Ajax.BeginForm("SplSvcDet", "OnSDPSvcRpt", "", new AjaxOptions
                {
                    HttpMethod = "POST",
                    InsertionMode = InsertionMode.Replace,
                    LoadingElementId = "divloading",
                    UpdateTargetId = "ReportPart",
                    OnBegin = "ClearStatusMessage",
                    OnSuccess = "ConfirmationMessage",
                    OnFailure = "FailureMessage"
                }))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <div class="col-lg-6">
                                @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                                @Html.DropDownListFor(model => model.Country, Model.CountryList, "Select Country", new { @class = "form-control", @id = "Country" })
                                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-lg-6">
                                @Html.LabelFor(model => model.Operator, htmlAttributes: new { @class = "control-label col-md-2" })
                                @Html.DropDownListFor(model => model.Operator, new List<SelectListItem>(), "Select Operator", new { @class = "form-control", @id = "Operator" })
                                @Html.ValidationMessageFor(model => model.Operator, "", new { @class = "text-danger" })
                            </div>

                        </div>
                        <div class="form-group col-lg-offset-2 col-lg-8 col-lg-offset-2">
                            @Html.LabelFor(model => model.ReportType, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownListFor(model => model.ReportType, new List<SelectListItem>() { new SelectListItem { Text = "Service Details", Value = "Service Details" }, new SelectListItem { Text = "Subscriber Details", Value = "Subscriber Details" } }, "Select ReportType", new { @class = "form-control", @id = "ReportType" })
                            @Html.ValidationMessageFor(model => model.ReportType, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <div class="col-lg-6">
                                @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-lg-6">
                                @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                        <div class="box-footer">
                            <input type="submit" value="Display" class="btn btn-primary col-lg-offset-5" />
                        </div>

                }

            </div>
        </div>
    </div>
</div>

<hr />

<div id="ReportPart">
</div>

<div class="container">
    <div class="row">
        <div class="col-md-offset-5 col-md-2 col-md-offset-5">
            <div id="divloading" style="display:none;align-content:center">
                <img src="~/Content/Images/Loadinggif.gif" />
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    function ConfirmationMessage() {
        ej.widget.init($("#ReportPart"));
    }
    function FailureMessage() {
        $('#ReportPart').html("<div class='alert alert-danger alert-dismissable'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button><h4 class='text-center'>Some issue has occured, Unable to fetch details temporarily</h4></div>");
    }
    function ClearStatusMessage() {
        $('#ReportPart').empty();
    }

    $(document).ready(function () {
        $('#Country').change(function () {
            $.ajax({
                type: "post",
                url: '@Url.Action("GetOperatorList")',
                data: { Country: $('#Country').val() },
                datatype: "json",
                success: function (Operators) {
                    $('#Operator').empty();
                    $("#Operator").append('<option value="">Select Operator</option>');

                    $.each(Operators, function (i, Operator) {
                        $("#Operator").append('<option value="' + Operator.Value + '">' + Operator.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve Operators.');//+ ex);
                }
            });
        });

        $('#FromDate').datepicker()
          //.attr('readonly', 'readonly')
          .keypress(function (event) {
              if (event.keyCode == 8) {
                  event.preventDefault();
              }
          });

        $('#FromDate').change(function () {
            if (!moment($('#FromDate').val(), 'MM/DD/YYYY', true).isValid()) {
                $('#FromDate').val('');
            }
        });
        $('#ToDate').datepicker({ maxDate: 0 })
          //.attr('readonly', 'readonly')
          .keypress(function (event) {
              if (event.keyCode == 8) {
                  event.preventDefault();
              }
          });

        $('#ToDate').change(function () {
            if (!moment($('#ToDate').val(), 'MM/DD/YYYY', true).isValid()) {
                $('#ToDate').val('');
            }
        });
    });
    @*$(document).ready(function () {
        $('#Country').change(function () {
            $.ajax({
                type: "post",
                url: '@Url.Action("GetOperatorList")',
                data: { Country: $('#Country').val() },
                datatype: "json",
                success: function (Operators) {
                    $('#Operator').empty();
                    $("#Operator").append('<option value="">Select Operator</option>');

                    $.each(Operators, function (i, Operator) {
                        $("#Operator").append('<option value="' + Operator.Value + '">' + Operator.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve Operators.');//+ ex);
                }
            });
        });
    });*@

</script>

VAS-CRP/Views/OnSDPSvcRpt/SplSvcDetails.cshtml
@model OnSDPSvc.Infrastructure.ResultModel.SplSvcDetails
@*@{
    ViewBag.Title = "IraqZainOnSDPReport";
}*@

<h3>@ViewBag.Report</h3>


<div class="text-center text-primary h3">Special Services Details</div>


@(Html.EJ().Grid<OnSDPSvc.Infrastructure.ResultModel.SpecialServices>("SpecialServices")
                    .Datasource(Model.SpecialServices)
                    .AllowPaging()
                    .AllowFiltering()
                    .AllowSorting()
                    .FilterSettings(filter => { filter.FilterType(FilterType.Menu); })
                    .Columns(col =>
                    {
                        col.Field("ProductID").HeaderText("ProductID").Add();
                        col.Field("ServiceName").HeaderText("ServiceName").Add();
                        col.Field("ShortCode").HeaderText("ShortCode").Add();
                        col.Field("BillingStatus").HeaderText("BillingStatus").Add();
                        col.Field("Subscribers").HeaderText("Subscribers").Add();
                    }))



<div class="text-center text-primary h3">Special Services Subscriber Details</div>



@(Html.EJ().Grid<OnSDPSvc.Infrastructure.ResultModel.SpecialServicesSubscribers>("SpecialServicesSubscribers")
                    .Datasource(Model.SpecialServicesSubscribers)
                    .AllowPaging()
                    .AllowFiltering()
                    .AllowSorting()
                    .FilterSettings(filter => { filter.FilterType(FilterType.Menu); })
                    .Columns(col =>
                    {
                        col.Field("ProductID").HeaderText("ProductID").Add();
                        col.Field("ServiceName").HeaderText("ServiceName").Add();
                        col.Field("ShortCode").HeaderText("ShortCode").Add();
                        col.Field("MSISDN").HeaderText("MSISDN").Add();
                        col.Field("BillingStatus").HeaderText("BillingStatus").Add();
                        col.Field("LastTranDate").HeaderText("LastTranDate").Add();
                    }))


@*Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.

Source Error:


Line 31:
Line 32:
Line 33: @(Html.EJ().Grid<OnSDPSvc.Infrastructure.ResultModel.SpecialServicesSubscribers>
    ("SpecialServicesSubscribers")
    Line 34:                     .Datasource(Model.SpecialServicesSubscribers)
    Line 35:                     .AllowPaging()*@

VAS-CRP/Views/OnSDPSvcRpt/_SplSvcDetails.cshtml
@model OnSDPSvc.Infrastructure.ResultModel.SplSvcDetails

<h3>@ViewBag.Report</h3>


<div class="text-center text-primary h3">Special Services Details</div>


@(Html.EJ().Grid<OnSDPSvc.Infrastructure.ResultModel.SpecialServices>("SpecialServices")
                    .Datasource(Model.SpecialServices)
                    .AllowPaging()
                    .AllowFiltering()
                    .AllowSorting()
                    .FilterSettings(filter => { filter.FilterType(FilterType.Menu); })
                    .Columns(col =>
                    {
                        col.Field("ProductID").HeaderText("ProductID").Add();
                        col.Field("ServiceName").HeaderText("ServiceName").Add();
                        col.Field("ShortCode").HeaderText("ShortCode").Add();
                        col.Field("BillingStatus").HeaderText("BillingStatus").Add();
                        col.Field("Subscribers").HeaderText("Subscribers").Add();
                    }))



<div class="text-center text-primary h3">Special Services Subscriber Details</div>



@(Html.EJ().Grid<OnSDPSvc.Infrastructure.ResultModel.SpecialServicesSubscribers>("SpecialServicesSubscribers")
                    .Datasource(Model.SpecialServicesSubscribers)
                    .AllowPaging()
                    .AllowFiltering()
                    .AllowSorting()
                    .FilterSettings(filter => { filter.FilterType(FilterType.Menu); })
                    .Columns(col =>
                    {
                        col.Field("ProductID").HeaderText("ProductID").Add();
                        col.Field("ServiceName").HeaderText("ServiceName").Add();
                        col.Field("ShortCode").HeaderText("ShortCode").Add();
                        col.Field("MSISDN").HeaderText("MSISDN").Add();
                        col.Field("BillingStatus").HeaderText("BillingStatus").Add();
                        col.Field("LastTranDate").HeaderText("LastTranDate").Add();
                    }))


@*Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.

    Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

    Exception Details: System.InvalidOperationException: Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.

    Source Error:


    Line 31:
    Line 32:
    Line 33: @(Html.EJ().Grid<OnSDPSvc.Infrastructure.ResultModel.SpecialServicesSubscribers>
        ("SpecialServicesSubscribers")
        Line 34:                     .Datasource(Model.SpecialServicesSubscribers)
        Line 35:                     .AllowPaging()*@

VAS-CRP/Views/Shared/_Layout.cshtml
@*@using WebApplication.Extensions*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>VAS-CRP</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @*@Styles.Render("~/bundles/Content/ACustom/plugins/font-awesome/css")*@
    <link href="~/Content/ACustom/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    @Styles.Render("~/bundles/Content/ACustom/plugins/ionicons/css")
    @Styles.Render("~/bundles/Content/ACustom/bootstrap/css")
    @Styles.Render("~/bundles/Content/ACustom/dist/css")
    @Styles.Render("~/bundles/Content/ACustom/dist/css/skins")

    @Styles.Render("~/Content/ej/web/bootstrap-theme/ej.web.all.min.css")

    @*<link href="~/Content/ACustom/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

        <link href="~/Content/ACustom/plugins/ionicons/css/ionicons.min.css" rel="stylesheet" />

        <link href="~/Content/ACustom/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

        <link href="~/Content/ACustom/dist/css/admin-lte.min.css" rel="stylesheet" />

        <link href="~/Content/ACustom/dist/css/skins/_all-skins.min.css" rel="stylesheet" />


        <link href="~/Content/ej/web/bootstrap-theme/ej.web.all.min.css" rel="stylesheet" />*@

    @Scripts.Render("~/bundles/Content/ACustom/plugins/jquery/js")

    @Scripts.Render("~/Scripts/jsrender.min.js")
    <script src="~/Scripts/jquery.easing.1.3.js"></script>
    @Scripts.Render("~/Scripts/ej/web/ej.web.all.min.js")
    <script src="~/Scripts/ej/common/ej.unobtrusive.min.js"></script>

    @RenderSection("menu", required: false)
    @Scripts.Render("~/bundles/Content/ACustom/bootstrap/js")
    @Scripts.Render("~/bundles/Content/ACustom/plugins/slimscroll/js")
    @Scripts.Render("~/bundles/Content/ACustom/plugins/fastclick/js")
    @Scripts.Render("~/bundles/Scripts/Shared/Layout")
    @Scripts.Render("~/bundles/Content/ACustom/dist/js")


    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script src="~/Scripts/moment.min.js"></script>
    <link href="~/Scripts/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui.min.js"></script>

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a href="@Url.Action("Welcome", "Home" )" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">
                    <b>Og</b>
                </span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">
                    <img src="~/Content/Images/VASLogo.jpg" width="220" height="48" />
                </span>
            </a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                    <ul class="nav navbar-nav">
                        @*<i class="fa fa-music" aria-hidden="true"></i>*@
                        <li class="active"><a href="#"><i class="fa fa-2x fa-music" aria-hidden="true"></i><span class="h3">  Link </span><span class="sr-only">(current)</span></a></li>
                        <li><a href="#"><i class="fa fa-2x fa-home" aria-hidden="true"></i>Link</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-2x fa-anchor" aria-hidden="true"></i>Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#"><i class="fa fa-2x fa-music" aria-hidden="true"></i>Action</a></li>
                                <li><a href="#"><i class="fa fa-2x fa-music" aria-hidden="true"></i>Another action</a></li>
                                <li><a href="#"><i class="fa fa-2x fa-music" aria-hidden="true"></i>Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#"><i class="fa fa-2x fa-music" aria-hidden="true"></i>Separated link</a></li>
                                <li class="divider"></li>
                                <li><a href="#"><i class="fa fa-2x fa-music" aria-hidden="true"></i>One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="navbar-custom-menu">

                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="hidden-xs">Hello  @Session["Username"] </span>
                                <span><i class="fa fa-fw fa-user fa-2x user-image"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="user-body">
                                    <div class="row">
                                        <div class="text-center">
                                            <a href="#">@*Role*@</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>

                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="text-center">
                                        <a href="@Url.Action("Logout", "Auth" )" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    @*<ul class="nav navbar-nav">
                            @Html.Partial("_LoginPartial")
                            <li>
                                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                            </li>
                        </ul>*@
                </div>
            </nav>
        </header>
        <aside class="main-sidebar">
            <section class="sidebar">
                <ul class="sidebar-menu">
                    <li class="header text-bold text-lime text-center"> Reports</li>
                    <li id="left-sidebar-menu-dashboard" class="treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>OnSDP Services</span> <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li id="left-sidebar-menu-dashboard-dashboardV1"><a href="@Url.Action("OnSDPSvc", "OnSDPSvcRpt" )"><i class="fa fa-circle-o"></i> Filtered Details</a></li>
                            <li id="left-sidebar-menu-dashboard-dashboardV1"><a href="@Url.Action("KuwaitZainOnSDPReport", "OnSDPSvcRpt" )"><i class="fa fa-circle-o"></i> Kuwait Zain</a></li>
                            <li id="left-sidebar-menu-dashboard-dashboardV2"><a href="@Url.Action("KuwaitOoredooOnSDPReport", "OnSDPSvcRpt" )"><i class="fa fa-circle-o"></i> Kuwait Ooredoo</a></li>
                            <li id="left-sidebar-menu-dashboard-dashboardV2"><a href="@Url.Action("IraqZainOnSDPReport", "OnSDPSvcRpt" )"><i class="fa fa-circle-o"></i> Iraq Zain</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
        </aside>
        <div class="content-wrapper">
            <section class="content-header">
                @*<h1>
                        @ViewBag.Title
                        <small>@ViewBag.SubTitle</small>
                    </h1>*@

            </section>
            <section class="content">
                @RenderBody()
            </section>
        </div>

        <footer class="main-footer">

            <strong>One Global - VAS</strong>
        </footer>

    </div>


    @*<script src="~/Content/ACustom/plugins/jquery/js/jQuery-2.1.4.min.js"></script>


        <script src="~/Scripts/jsrender.min.js"></script>

        <script src="~/Scripts/jquery.easing.1.3.js"></script>
        <script src="~/Scripts/ej/web/ej.web.all.min.js"></script>



        <script src="~/Content/ACustom/bootstrap/js/bootstrap.min.js"></script>

        <script src="~/Content/ACustom/plugins/slimscroll/js/jquery.slimscroll.min.js"></script>

        <script src="~/Content/ACustom/plugins/fastclick/js/fastclick.min.js"></script>

        <script src="~/Scripts/Shared/_Layout.js"></script>

        <script src="~/Content/ACustom/dist/js/app.js"></script>*@




    @Html.EJ().ScriptManager()
    @RenderSection("scripts", required: false)

    

    <div id='preloader'>
        <div id='status'>
            <img alt='' height='64' src='~/Content/Images/Triangular Circle.gif' width='64' />
        </div>
    </div>
    <script type="text/javascript">
        $(window).load(function () {

            $("#status").fadeOut("slow");

            $("#preloader").delay(500).fadeOut("slow").remove();

        })
    </script>
    <style type="text/css">
        #preloader {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #222222;
            z-index: 99999;
            height: 100%;
        }

        #status {
            position: absolute;
            left: 50%;
            top: 50%;
            width: 64px;
            height: 64px;
            margin: -32px 0 0 -32px;
            padding: 0;
        }
    </style>


</body>
</html>

VAS-CRP/Views/Shared/_LayoutD.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>